#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  gather_facts: no

  tasks:
  -  name:
     ansible.builtin.file:
       src: "~/settings/{{item}}"
       dest: "~/{{item}}"
       state: link
       force: yes
       follow: no
     loop:
       - .bashrc
       - .emacs.d
